version: "3.8"

services:
  api:
    image: philoupy/file-server
    command: npm run start
    ports:
      - 3001:3001
    volumes:
      - /mnt/vol01:/file-server
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
